# Generated by Django 5.2.3 on 2025-06-21 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('url', models.TextField()),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('langs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('c#', 'C#'), ('python', 'Python'), ('go', 'Go'), ('java', 'Java'), ('js', 'JS')], max_length=20), blank=True, default=list, size=None)),
                ('domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('docs', 'Documentation'), ('game_dev', 'Game Development'), ('backend', 'Backend'), ('mobile', 'Mobile Development'), ('frontend', 'Frontend')], max_length=20), blank=True, default=list, size=None)),
                ('good_first', models.BooleanField(default=False)),
            ],
        ),
    ]
