# Generated by Django 5.2.3 on 2025-06-21 18:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_pic_url_alter_user_pref_domains_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pref_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('docs', 'Documentation'), ('game_dev', 'Game Development'), ('mobile', 'Mobile Development'), ('backend', 'Backend'), ('frontend', 'Frontend')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='pref_langs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('c#', 'C#'), ('java', 'Java'), ('js', 'JS'), ('go', 'Go'), ('python', 'Python')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
