# Generated by Django 5.2.3 on 2025-06-21 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_pref_domains_alter_user_pref_langs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pref_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('docs', 'Documentation'), ('game_dev', 'Game Development'), ('backend', 'Backend'), ('mobile', 'Mobile Development'), ('frontend', 'Frontend')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='pref_langs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('c#', 'C#'), ('python', 'Python'), ('go', 'Go'), ('java', 'Java'), ('js', 'JS')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
